### ISSUE TITLE
[request] Automatically set custom status

### ISSUE THREAD

**Issue by Tliks** [Raphiiko/OyasumiVR#100]
I would like a function that automatically switches to custom status (e.g. sleeping) when entering sleep mode, and automatically cancels it when exiting sleep mode.

Since OyasumiVR offers a variety of functions, there is currently little to do before sleeping but I feel that setting a custom status is the only exception.

If there is a factor that makes implementation difficult, I would like to know it.
thank you.

**Comment by Raphiiko** [comment]
This is indeed something I've been planning on doing, but just haven't gotten to yet. You can expect it in some future release, I just can't promise yet when I'll get to it.

**Comment by Tliks** [comment]
Understood. This is the feature I want most for OyasumiVR and I look forward to the day it is released.

**Comment by Raphiiko** [comment]
This feature has been added and will be included with the upcoming update!
![image](https://github.com/Raphiiko/OyasumiVR/assets/111654848/16e36e7c-0fe3-4d5f-bd4b-bb7511b5c75f)
