### ISSUE TITLE
Battery level power automation issue?

### ISSUE THREAD

**Issue by soupfend** [Raphiiko/OyasumiVR#111]
I'm standing here just after getting in vrc with everything charged trying to calibrate my fullbody while trackers and controllers are turning off. 
steamvr 2.6.2
index controllers
vive 3.0 trackers
[logs.zip](https://github.com/user-attachments/files/16061074/logs.zip)

![image](https://github.com/Raphiiko/OyasumiVR/assets/174287755/84d10e32-e361-4ad8-91df-3a4c2160f784)
![image](https://github.com/Raphiiko/OyasumiVR/assets/174287755/3e192a36-d875-4876-87c8-13ee2a29ec0d)

**Comment by Raphiiko** [comment]
That's indeed quite odd, I'll be giving this a test later!

**Comment by Raphiiko** [comment]
I could indeed reproduce this issue. It should be fixed in 1.13.3 which will be out in a few minutes!
