### ISSUE TITLE
[Request] Automatically run shutdown sequence after sleep mode enabled in a specify time

### ISSUE THREAD

**Issue by Jaydenha09** [Raphiiko/OyasumiVR#114]
the current setting is very confusing, I have no idea on how to set it run the shutdown sequence after sleep mode enabled, there arent much description about it, it would be better if it can run shutdown sequence after sleep mode enabled in a specify time

**Comment by Raphiiko** [comment]
There is currently already a trigger for this.

If you take this configuration for example, it will activate the shutdown sequence when the sleep mode has been enabled for 1 minute:
![image](https://github.com/user-attachments/assets/b7e46519-1596-4877-a269-224da735c878)

If you want it to activate immediately when the sleep mode enables, just set the duration threshold to 00:00:00.

**Comment by Raphiiko** [comment]
As this request doesn't seem to regard a bug or new functionality, I'll close the issue.
If you need any additional support with this feature, feel free to hop by in [the discord](https://discord.gg/7MqdPJhYxC) and I'll be happy to help you further.
