### ISSUE TITLE
Pulsoid intergeration not working 

### ISSUE THREAD

**Issue by BeigeAnimal** [Raphiiko/OyasumiVR#122]
I went to the integration tab to link my pulsoid account, log into my pulsoid account, and click authorize but OyasumiVR doesn't show my account is linked or seems to get smart watch data. I've tried the beta and stable branch on steam and I've tried several web browsers (Chrome based and firefox) as well as wiping my configs

In the console for OyasumiVR, when I click authorize app the console does give a response however it just won't link
![urnsfwjVJi](https://github.com/user-attachments/assets/6c2e7dca-3d1f-48c5-93b8-8fe79f4ec239)

I have done the one-time purchase too

**Comment by Raphiiko** [comment]
That's very odd. Looks like oyasumi receives the response from Pulsoid just fine, but something goes wrong after that in your case. 

A few questions / things to try to narrow the issue down:

1. There _should_ be additional logging should the parsing of that URL fail. Log files are located in `%appdata%/co.raphii.oyasumi/logs`. Do you see any relevant warnings/errors (most likely tagged "[PulsoidService]"? Alternatively, feel free to shoot me your log files on discord (@raphiiko) or by mail on iam[at]raphii[dot]co and I'd be happy to take a look.

2. If you go to `Settings -> Advanced Settings -> Open DevTools`, a new window should open. Go to the Console tab. If you then try to link your Pulsoid account, do any errors appear in the console?

If neither of these have any results, I'll add some additional logging to the beta to get a bit more info about what's going on.

**Comment by BeigeAnimal** [comment]
@Raphiiko I ended up doing those two things, I didn't see any errors or warnings in logs or in console.

**Comment by Raphiiko** [comment]
Gotcha. I'll put out a build with some extra logging tomorrow.

**Comment by Raphiiko** [comment]
@BeigeAnimal It's available now. To access it, please use `BeigeAnimal123` as your beta access code in Steam:
![image](https://github.com/user-attachments/assets/a8fdfc21-4d0a-468b-9763-b7655facfca7)

After switching to that branch, to get the logs, please do the following:
1. Make sure OyasumiVR isn't running
2. Delete all log files in `%appdata%\co.raphii.oyasumi\logs`
3. Start OyasumiVR
4. Ensure you're on build `37365fa`: You can see this either by hovering over "OyasumiVR" in the window title, at the bottom of the about screen, or in the splash screen. If the id doesn't match, quit oyasumi, make sure you're on the correct branch, use Steam to verify integrity of your files, and start again from step 1.
5. Try to link your Pulsoid account. 
6. Once it's failed, wait like 10 seconds to ensure all logs are written to disk
7. Zip up all the newly created log files in `%appdata%\co.raphii.oyasumi\logs`.

If you can then send me the zip file either via discord or email, I can take a look at what's going on.

**Comment by Raphiiko** [comment]
@BeigeAnimal Scratch all of that! Even though I couldn't seem to yesterday, I could just reproduce the same issue.

I think I figured out what's going wrong, from what I can tell there was likely some breaking change upstream. It appears that the way `Url` parses its `pathname` property seems to have changed. I am not sure why or how that behaviour changed, as this is a standard browser API, which really don't ever get breaking changes like that. 

Regardless, the issue _should_ have been fixed. The build id for your personal debugging branch should now be `f2b1ae8`. I've also deployed the fix without all the additional debug logging to the regular beta branch. 

If you could please confirm if this fixes the issue for you as well, I'll release the fix asap.

**Comment by BeigeAnimal** [comment]
@Raphiiko yep that fixed it, thx

**Comment by Lioncat6** [comment]
Even pasting the url `oyasumivr://integration/pulsoid/v1/redirect#token_type=bearer&access_token=xxxxxx&expires_in=315360000&scope=data:heart_rate:read,profile:read&state=xxxxxx` doesn't prompt the open in application, which leaves me to believe Oyasumi didn't properly register the URI registry entry, explaining why my browser didn't even try to open it



Looking in my registry, there's no entry for `oyasumivr` in the location where those kinds of deep links would be, so this is the theory I'm leaning towards... 

<img width="433" height="381" alt="Image" src="https://github.com/user-attachments/assets/6ee339fd-294a-4acf-911f-f2539e004098" />

Using the command line argument for the deep link did work, however:

<img width="1362" height="808" alt="Image" src="https://github.com/user-attachments/assets/4d3a76b0-a51e-44f4-9c4d-7416d3ededa9" />

**Comment by Raphiiko** [comment]
Hmm, it indeed seems that after the last feature release the entry is no longer registered automatically. Something might have changed between versions of the deep link plugin when upgrading from Tauri v1 to v2.

As this is a different issue from this one it can be tracked in #152.
