### ISSUE TITLE
I cant install OyasumiVR

### ISSUE THREAD

**Issue by UsagiLoona** [Raphiiko/OyasumiVR#41]
When installing the program I get the message:

"install missing runtimes

 the following runtimes that are needed by OyasumiVR are either too outdated or not installed on your system 

-.NET Runtime 7.0.10 

-ASP.NET Core Runtime 7.0.10"

  I have tried several times to install both runtimes, making sure that it is the correct version, restarting the pc, uninstalling and reinstalling oyasumiVR but I still get the same error.
![Screenshot 2023-09-07 144102](https://github.com/Raphiiko/OyasumiVR/assets/144348084/028100b1-9f0f-4268-a929-cd7ab856cd93)

**Comment by Raphiiko** [comment]
@UsagiLoona Could you please verify if this issue still occurs for you with the [Development build](https://github.com/Raphiiko/OyasumiVR/releases/tag/oyasumi-vDEV)?

**Comment by UsagiLoona** [comment]
@Raphiiko yes, the problem still there

**Comment by Raphiiko** [comment]
Hmm, that's odd, I thought I fixed that in the dev build.
Do you happen to have the output of `dotnet --list-runtimes` for me?

**Comment by UsagiLoona** [comment]
@Raphiiko 
![Screenshot 2023-09-07 151234](https://github.com/Raphiiko/OyasumiVR/assets/144348084/46f6eff9-c301-4779-991d-d52a33b08c3d)

**Comment by Raphiiko** [comment]
Hmmm, that does look like you're still lacking the needed runtimes. I would expect `Microsoft.NETCore.App 7.0.10` and `Microsoft.AspNetCore.App 7.0.10` to appear in that list, like here: 
![image](https://github.com/Raphiiko/OyasumiVR/assets/111654848/8b59045b-cd0a-4ac8-b1f6-bccaa9636f6b)

OyasumiVR should attempt to install these automatically if you press the button, but I assume you've already tried that, so I can only assume the installation for those somehow fails. 

From [this](https://dotnet.microsoft.com/en-us/download/dotnet/7.0) page, have you tried installing these? (Plan A, try Plan B only if Plan A does not work) 
![image](https://github.com/Raphiiko/OyasumiVR/assets/111654848/8a71e5a6-76c3-491e-99a9-ff953a36ce88)

**Comment by UsagiLoona** [comment]
I tried the plan A before, so Ill try the plan B

**Comment by Raphiiko** [comment]
One other thing I can recommend trying is uninstalling those older .net versions. Try uninstalling v3, maybe even v6 too if just uninstalling v3 does not work.

**Comment by UsagiLoona** [comment]
it worked with the plan B! thank u so much for your help and especially for your time <3<3<3<3<3<3<3<3<3<3

**Comment by Raphiiko** [comment]
No worries! Glad you got it to work :)
