### ISSUE TITLE
[Request] Option to disable all VR overlay prompts

### ISSUE THREAD

**Issue by ZenithVal** [Raphiiko/OyasumiVR#42]
I've been using 1.7.2 for a long time and recently picked up the Steam version which is v1.9.0. The overlays are new to me.

The overlays are neat but a little unnecessary for some of us. Can we get an option to completely disable the VR startup logo and the Activate/Deactivate prompts? I personally use Oyasumi for the one click power tuning option & batch tracker disabling via Steam desktop view.

**Comment by Raphiiko** [comment]
@ZenithVal I currently don't have any plans for disabling the overlay splash screen.

As for the prompts, you should be able to disable most of them in **Settings** -> 
**Notifications**. If you get any prompts or notifications that you cannot disable here, let me know and I'll see to having them added.
