### ISSUE TITLE
Get HR data from Pulsoid without "BRO" subscription

### ISSUE THREAD

**Issue by shinenami** [Raphiiko/OyasumiVR#46]
So i've been using [this app](https://github.com/200Tigersbloxed/HRtoVRChat_OSC) for a while now, and it seems theres actually a way to retrieve HR data from pulsoid without requiring you to have their subscription, [by using access_token](https://github.com/200Tigersbloxed/HRtoVRChat_OSC/wiki/Upgrading-from-Pulsoid-to-PulsoidSocket#retrieving-a-pulsoidkey-access_token). Not sure if its something you could implement but would be nice. I think it's in their [API](https://docs.pulsoid.net/access-token-management/oauth2-implicit-grant)

**Comment by Raphiiko** [comment]
Whether a Pulsoid subscription is required for one of their integrations depends on the individual agreement between each developer and Pulsoid. As I'm still in talks with them, the current Pulsoid integration you see in the development build is still very much a WIP: what this would look like has not entirely been determined yet.

I can say that eventually, this specific integration might require some form of subscription or one-time payment, at least initially.
