### ISSUE TITLE
Feature request: Whitelist friends bulk import

### ISSUE THREAD

**Issue by inkuxuan** [Raphiiko/OyasumiVR#55]
Searching for friends when creating a whitelist is somehow very laggy. Sometimes stuck for even a minute.
Would appreciate if the whitelist can be manually edited using a configuration file or anything likewise.
(Right now I'm manually editing the JSON file in %UserProfile%. However this could be risky for some users)

**Comment by inkuxuan** [comment]
@Raphiiko 
FYI it lags when
- I start typing one or two characters (that probably triggers a search)
- I click at "Add friends" button, and then close the popup without doing anything

And I have ~700 friends.

**Comment by Raphiiko** [comment]
Performance has possibly been improved on the latest development build. Awaiting testing.

**Comment by Raphiiko** [comment]
Closing this as an improvement to the performance of the friend selection modal has been made and will be released with v1.11. I might add an import/export function later down the line, but for now this is not planned.
