### ISSUE TITLE
OyasumiVR flagged as PUP by Bitdefender AV

### ISSUE THREAD

**Issue by TheRealDanini** [Raphiiko/OyasumiVR#60]
As the title of this issue states, Bitdefender Antivirus detects OyasumiVR as a PUP and labels it as a cryptominer. I am posting this issue to let the developer know that OyasumiVR conflicts with Bitdefender so that the conflict can be resolved as this is 100% a false positive from the anti virus. I will also see if I can submit a sample to Bitdefender to correct the false positive.

**Comment by Raphiiko** [comment]
Thanks for submitting it as a false positive. Sadly these things just pop up from time to time and there's not much else that can be done. 1.7.0 [falsely got flagged](https://github.com/tauri-apps/tauri/issues/2486#issuecomment-1588254687) by windows defender as a trojan, but this was already not the case anymore with the next patch release. OyasumiVR is definitely [not the only tauri app](https://github.com/tauri-apps/tauri/issues?q=is%3Aissue+trojan+is%3Aclosed+) dealing with this issue. 

I've just released 1.10.4 a couple of minutes ago, so if you were experiencing this issue with 1.10.3, this particular instance might already be resolved.

**Comment by TheRealDanini** [comment]
Updating this issue as it still conflicts with bitdefender. Resubmitted the sample to bitdefender so lets see how it goes this time.

Ver 1.10.4-STEAM
