### ISSUE TITLE
Support for MQTT & Home Assistant

### ISSUE THREAD

**Issue by AtryFox** [Raphiiko/OyasumiVR#61]
A simple MQTT implementation publishing the sleeping state to a broker to allow control of things outside VR or your PC would be interesting. 

With this users could run automations in Home Assistant or other home automation software to control lights/fans/ACs/window shutters/heating and so much more, bascially allowing endless possibilities. 

Is anything like that in the pipeline? Would love to see it!

**Comment by Raphiiko** [comment]
As a long-time Home Assistant user myself it's something I've been wanting to add for a while now, but I've not yet had the time. At this point I can't say how soon that would be, as there are more things that still have higher priorities. However I can say it will likely be added in some future update.

**Comment by dubyatp** [comment]
+1 

As someone who uses a Quest 2 with PCVR, having lights on is a requirement for proper tracking with my controllers, and I really don't want to have the lights on if i'm asleep, it would be really nice to just have an automation trigger to HA to turn my lights on if motion is detected on my controllers.

**Comment by Raphiiko** [comment]
@AtryFox A very basic implementation of this is now in develop. It should land in the beta on Steam shortly. 

Currently, it only exposes the sleep mode to home assistant as a switch. 
However now that the functionality is there, I do plan on exposing more options.
I'll be adding those before the next feature update drops, but for now you can already play around with it. You'll find the option for it in the integration settings.

**Comment by Raphiiko** [comment]
It seems that right now, in release builds it doesn't really like dealing with insecure sockets. I'll have to see how I'm going to get around that some time later. Until then, you'll likely only be able to get this to work if you've got SSL enabled on your broker's websocket.

**Comment by AtryFox** [comment]
That's really cool, thanks for the update! Works flawlessly for me so far.
It seems like it not just requires SSL, but also a valid certificate? I don't have SSL certificates setup directly on my HA/broker machine, I just run everything behind a reverse proxy that's managing my certs. 
Pointing directly to my MQTT broker, Oyasumi doesn't connect. Setting up a reverse proxy host with valid certificate, that points to my broker and using that in Oyasumi works fine.

**Comment by Raphiiko** [comment]
I'll be closing this issue as by now I've exposed a bunch of Oyasumi's features over MQTT. The integration should land in the next release (v1.13) which shouldn't be too far off now.

![image](https://github.com/Raphiiko/OyasumiVR/assets/111654848/6fd3aec6-cfc7-4f1b-be8f-165254a298d7)
