### ISSUE TITLE
Auto-turn off tracker not working

### ISSUE THREAD

**Issue by alzahhar3** [Raphiiko/OyasumiVR#70]
I have it set to auto turn off tracker at around 15% charge when sleep mode is on but it doesn't work and trackers get to 0%

**Comment by Raphiiko** [comment]
- Are your trackers above 15% before OyasumiVR or the automation is started?
- Does this also happen at higher percentage thresholds (e.g. 50%?), in my experience my trackers die pretty quickly anytime they're below 20% regardless of if they've been turned off.
- Does this issue also occur when you turn off the checkbox for it to only run while sleep mode is active?

**Comment by alzahhar3** [comment]
Thanks for the reply!

1. yes it’s all above 15% before oyasumiVR is started. Although I have oyasumiVR start with steamVR and I start the trackers after that, so not sure if the sequence here matters. 
what do you mean by “automation is started”? I only have that specific option turned on but not the shutdown sequence automation if that matters. 

2. I’m not sure I’ve only tried 15%. In my experience my tundra trackers last quite a bit even at 15% unlike my vive trackers, but I saw it slowly go below 15% and die without being turned off automatically. 

3. I’ll have to try this one out and report back!

**Comment by Raphiiko** [comment]
Sorry for the late reply, life's been incredibly busy this year ^^'

I've now fixed this in develop. This fix will come with the next release, and should be in the new development build in a minute.
