### ISSUE TITLE
Character mid air?

### ISSUE THREAD

**Issue by ctrlBIRDdelete** [Raphiiko/OyasumiVR#72]
I've got an issue with avatars using Gogoloco being in a lay down pose before Oyasumi's sleep mode kicks in and the animation switches, this usually causes the avatar to float in the air in the sleeping position. From what i've noticed the ground offset in Gogoloco menu changes to some really high number. Trying to alter it manually breaks the sleeping animations as my avatar stands up

**Comment by Raphiiko** [comment]
Sorry for the late reply, life's been kinda busy this year ^^'

This is indeed correct. The laying down "poses" controlled by OyasumiVR are part of GogoLoco's sleep mode, and not identical to the other poses included with that package. 

Instead, the float parameter (the ground offset you're talking about) is repurposed to control the sleeping pose while GoGoLoco's sleep mode is active. This means that you cannot use a custom ground offset while GogoLoco's sleep mode is active.

It's recommended that before going to sleep, you make sure your float value is already at 0, and instead use a playspace mover to make sure you're at the right height. (Like the one included with [OVR Advanced Settings](https://store.steampowered.com/app/1009850/OVR_Advanced_Settings/) for example.
