### ISSUE TITLE
Running Oyasumi as admin disables interaction via SteamVR overlay

### ISSUE THREAD

**Issue by ZenithVal** [Raphiiko/OyasumiVR#8]
In order to access GPU Automations, Oyasumi must be run with elevated permissions. This functions correctly but doing so disables the ability to interact with the program via the default SteamVR overlay. (like task manager and other elevated tasks) Running SteamVR as admin could potentially be a solution for this but if there's a workaround besides that it would be appreciated.

A optional native SteamVR overlay app like advanced settings could solve this issue. Alternativly the GPU automation settings could be handed off from the standard UI to an elevated sub program, this would also remove the need to reboot the program if you forgot to initiate it as admin.

**Comment by Raphiiko** [comment]
I've been running into the same issue. Currently the workaround I use is to set my overlay (XSOverlay) to always run as administrator, and have it start with SteamVR. That way I only get the UAC prompt once before putting on the headset, which isn't too intrusive. 

I do like the idea of moving the functionality that requires elevation to a sidecar process. Once I finish what I'm working on I'll see if I can figure out how to get that to work.

**Comment by Raphiiko** [comment]
I've moved the required functionality to a sidecar that asks for elevation, so there no longer should be a problem with interacting with the main window through overlays, when giving Oyasumi elevated permissions. 

It's currently still in `develop`, so it'll come with the next release. If you'd like to try it before then, you can download the last [development build](https://github.com/Raphiiko/Oyasumi/releases/tag/oyasumi-vDEV)!
