### ISSUE TITLE
Disabling Discord Rich Presence

### ISSUE THREAD

**Issue by Louka3000** [Raphiiko/OyasumiVR#84]
I don't see any way to disable Discord Rich Presence. Could you add an option to? I'd rather show my friends which VRChat world I'm in rather than if I'm sleeping or not...

**Comment by Pacmard** [comment]
Hi! There is such option in the latest release (including steam)! Its in Settings > General settings
![image](https://github.com/Raphiiko/OyasumiVR/assets/15702565/1122cd04-9938-450c-8c23-33bf3d8091c3)

**Comment by Louka3000** [comment]
Thanks, I didn't see ^^
