### ISSUE TITLE
1.0 Base station standby

### ISSUE THREAD

**Issue by Myrkie** [Raphiiko/OyasumiVR#85]
by default SteamVR does support standby modes for 1.0 base stations but using shutdown sequence in Oyasumi with SteamVR shutdown enabled will cause SteamVR to skip setting base stations to standby mode, and Oyasumi built in base station standby and sleep modes only support 2.0 base stations in both tool tip and practice.

**Comment by Raphiiko** [comment]
OyasumiVR currently only supports 2.0 base stations, as that's what I personally have.

I think I'm relatively familiar with how the 1.0's work so I wouldn't mind trying to add support for them, but as I don't own any 1.0's anymore I don't really have a way to work on this. As they're pretty much outdated hardware by this point I don't have any plans on getting one, so unless someone is willing to send me one to develop with it's unlikely to ever be added.

As for basestations not turning off when SteamVR is stopped by Oyasumi, I don't think there's much I can do about that. However, to my knowledge 1.0 base stations work on a timeout duration rather than dedicated on-off commands, so unless SteamVR sets this to a very long duration when turning them on, they theoretically should eventually turn off some time after SteamVR has quit.

**Comment by Myrkie** [comment]
> OyasumiVR currently only supports 2.0 base stations, as that's what I personally have.
> 
> I think I'm relatively familiar with how the 1.0's work so I wouldn't mind trying to add support for them, but as I don't own any 1.0's anymore I don't really have a way to work on this. As they're pretty much outdated hardware by this point I don't have any plans on getting one, so unless someone is willing to send me one to develop with it's unlikely to ever be added.
> 
> As for 1.0 basestations not turning off when SteamVR is stopped by Oyasumi, I don't think there's much I can do about that. However, to my knowledge 1.0 base stations work on a timeout duration rather than dedicated on-off commands, so unless SteamVR sets this to a very long duration when turning them on, they theoretically should eventually turn off some time after SteamVR has quit, even when SteamVR doesn't turn them off itself.

1. 1.0 base station support has been written time and time again in multiple different methods even within python and rust alike https://github.com/chenxiaolong/svrbsctl https://github.com/risa2000/lhctrl I may look into implementing it myself with help of some friends depending how rust treats me.
2.  as for this part I can confirm that they do stay on, powermanagment is enabled within steamvr it self but if Oyasumi shuts down steamvr as apart of the shutdown sequence they will remain on until steamvr is shut off in the regular way and only know this as they have stayed over for multiple nights.

**Comment by Raphiiko** [comment]
I'm sure we would be able to get the functionality in here with some community testing, however the initial implementation is only one part of the issue. The other is maintaining it, which with me not having the hardware becomes a lot more complicated. As this niche project is mostly a one-man-show (as opposed to a community project), I try to avoid situations where I'd start needing the help of other people to maintain this project as much as I can. That includes adding support for hardware I don't have the means to test. 

If you have the technical ability to look into this, I could suggest keeping it external. OyasumiVR exposes the state of the sleep mode over OSC (& OSCQuery), which you could listen or poll for, and then trigger your own scripts for turning your basestations on/off accordingly.

**Comment by Myrkie** [comment]
> I'm sure we would be able to get the functionality in here with some community testing, however the initial implementation is only one part of the issue. The other is maintaining it, which with me not having the hardware becomes a lot more complicated. As this niche project is mostly a one-man-show (as opposed to a community project), I try to avoid situations where I'd start needing the help of other people to maintain this project as much as I can. That includes adding support for hardware I don't have the means to test.
> 
> If you have the technical ability to look into this, I could suggest keeping it external. OyasumiVR exposes the state of the sleep mode over OSC (& OSCQuery), which you could listen or poll for, and then trigger your own scripts for turning your basestations on/off accordingly. (Edit: Or maybe even easier, check whether steamvr's process is running and run the scripts to turn off your base stations once it stops).

I understand your point, I would offer to implement and maintain myself but I do not know rust ill have to consider an alternative and not use shutdown sequence. cheers!

**Comment by Raphiiko** [comment]
Best of luck! I'll be sure to revisit this if the situation does arise 👍
