### ISSUE TITLE
Error at initialization

### ISSUE THREAD

**Issue by Delizzs** [Raphiiko/OyasumiVR#99]
I got this error showing each time I start oyasumi in steam:
oyasumivr could not completely initialize, and therefore failed to start.

**Comment by SticksDev** [comment]
Please provide a logfile, This can be found in `%APPDATA%/co.raphii.oyasumi/logs`.

**Comment by Raphiiko** [comment]
I (think) we already talked in Discord, but just in case that wasn't you, if you could please DM me your log files that would be great!

**Comment by Raphiiko** [comment]
I'll be closing this in the mean time. Feel free to reopen this issue if necessary.

**Comment by Delizzs** [comment]
Hello, yes that was me on the discord. Ty for your help❤️
